[project]
name = "hybrid-athlete-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beanie>=2.2.0",
    "fastapi>=0.141.1",
    "motor>=3.7.1",
    "pandas>=3.0.5",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "uvicorn[standard]>=0.52.3",
]
